config/routes.rb
Rails.application.routes.draw do
  resources :bots
  post 'callback/line/:botname', to: 'callback#line'
  post 'callback/telegram/:botname', to: 'callback#telegram'
  resources :messages
  root to: 'home#index'
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/bot.rb
# ## Schema Information
#
# Table name: `bots`
#
# ### Columns
#
# Name                | Type               | Attributes
# ------------------- | ------------------ | ---------------------------
# **`id`**            | `bigint`           | `not null, primary key`
# **`config_store`**  | `json`             |
# **`name`**          | `text`             |
# **`platform`**      | `text`             |
# **`created_at`**    | `datetime`         | `not null`
# **`updated_at`**    | `datetime`         | `not null`
#
class Bot < ApplicationRecord
  store :config_store, accessors: %i[line_client_token telegram_client_token]
end

app/controllers/bots_controller.rb
class BotsController < ApplicationController
  before_action :set_bot, only: %i[ show edit update destroy ]

  # GET /bots or /bots.json
  def index
    @bots = Bot.all
  end

  # GET /bots/1 or /bots/1.json
  def show
  end

  # GET /bots/new
  def new
    @bot = Bot.new
  end

  # GET /bots/1/edit
  def edit
  end

  # POST /bots or /bots.json
  def create
    @bot = Bot.new(bot_params)

    respond_to do |format|
      if @bot.save
        format.html { redirect_to @bot, notice: "Bot was successfully created." }
        format.json { render :show, status: :created, location: @bot }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bots/1 or /bots/1.json
  def update
    respond_to do |format|
      if @bot.update(bot_params)
        format.html { redirect_to @bot, notice: "Bot was successfully updated." }
        format.json { render :show, status: :ok, location: @bot }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bots/1 or /bots/1.json
  def destroy
    @bot.destroy!

    respond_to do |format|
      format.html { redirect_to bots_path, status: :see_other, notice: "Bot was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bot
      @bot = Bot.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bot_params
      params.require(:bot).permit(:name, :platform, :config_store)
    end
end

app/helpers/bots_helper.rb
module BotsHelper
end

app/views/bots/_bot.html.erb
<div id="<%= dom_id bot %>">
  <p>
    <strong>Name:</strong>
    <%= bot.name %>
  </p>

  <p>
    <strong>Platform:</strong>
    <%= bot.platform %>
  </p>

  <p>
    <strong>Config store:</strong>
    <%= bot.config_store %>
  </p>

</div>

app/views/bots/_form.html.erb
<%= form_with(model: bot) do |form| %>
  <% if bot.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(bot.errors.count, "error") %> prohibited this bot from being saved:</h2>

      <ul>
        <% bot.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_area :name %>
  </div>

  <div>
    <%= form.label :platform, style: "display: block" %>
    <%= form.text_area :platform %>
  </div>

  <div>
    <%= form.label :config_store, style: "display: block" %>
    <%= form.text_field :config_store %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/bots/edit.html.erb
<h1>Editing bot</h1>

<%= render "form", bot: @bot %>

<br>

<div>
  <%= link_to "Show this bot", @bot %> |
  <%= link_to "Back to bots", bots_path %>
</div>

app/views/bots/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Bots</h1>

<div id="bots">
  <% @bots.each do |bot| %>
    <%= render bot %>
    <p>
      <%= link_to "Show this bot", bot %>
    </p>
  <% end %>
</div>

<%= link_to "New bot", new_bot_path %>

app/views/bots/new.html.erb
<h1>New bot</h1>

<%= render "form", bot: @bot %>

<br>

<div>
  <%= link_to "Back to bots", bots_path %>
</div>

app/views/bots/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @bot %>

<div>
  <%= link_to "Edit this bot", edit_bot_path(@bot) %> |
  <%= link_to "Back to bots", bots_path %>

  <%= button_to "Destroy this bot", @bot, method: :delete %>
</div>